--- !ruby/object:RPerf::Resource 
cpu_average: !ruby/object:RPerf::Resource::CPU 
  name: AVERAGE
  system: 4833580
  time: 2013-01-03 18:21:56.656049 +09:00
  user: 8057540
  wait: 796250750
cpus: 
- !ruby/object:RPerf::Resource::CPU 
  name: "0"
  system: 2466790
  time: 2013-01-03 18:21:56.656419 +09:00
  user: 4042570
  wait: 394622880
- !ruby/object:RPerf::Resource::CPU 
  name: "1"
  system: 2366790
  time: 2013-01-03 18:21:56.656482 +09:00
  user: 4014960
  wait: 401627860
disk_ios: 
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram0
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.075778 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram1
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.076262 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram2
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.080112 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram3
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.080573 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram4
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.081915 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram5
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.082285 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram6
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.083608 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram7
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.084024 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram8
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.084552 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram9
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.084883 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram10
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.085324 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram11
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.085725 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram12
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.086142 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram13
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.087070 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram14
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.089111 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: ram15
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.089476 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: loop0
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.090971 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: loop1
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.091162 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: loop2
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.092604 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: loop3
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.092850 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: loop4
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.093743 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: loop5
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.094032 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: loop6
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.094266 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: loop7
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.094408 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: sr0
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.096059 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: fd0
  queue_length_time: 0
  read_count: 0
  read_data_size: 0
  time: 2013-01-03 18:21:57.096304 +09:00
  wait_time: 0
  write_count: 0
  write_data_size: 0
- !ruby/object:RPerf::Resource::DiskIO 
  name: sda
  queue_length_time: 3465552000000
  read_count: 325563
  read_data_size: 5543056384
  time: 2013-01-03 18:21:57.096582 +09:00
  wait_time: 490168000000
  write_count: 356228
  write_data_size: 8420671488
- !ruby/object:RPerf::Resource::DiskIO 
  name: sda1
  queue_length_time: 3198960000000
  read_count: 305761
  read_data_size: 5454451712
  time: 2013-01-03 18:21:57.097361 +09:00
  wait_time: 470656000000
  write_count: 351053
  write_data_size: 8203206656
- !ruby/object:RPerf::Resource::DiskIO 
  name: sda2
  queue_length_time: 266128000000
  read_count: 19651
  read_data_size: 87986176
  time: 2013-01-03 18:21:57.098086 +09:00
  wait_time: 42292000000
  write_count: 5175
  write_data_size: 217464832
filesystems: 
- !ruby/object:RPerf::Resource::Filesystem 
  free_size: 786034688
  mount_point: /run/shm
  time: 2013-01-03 18:21:56.863950 +09:00
  total_files: 191923
  total_size: 786116608
  used_files: 5
  used_size: 81920
- !ruby/object:RPerf::Resource::Filesystem 
  free_size: 5316870144
  mount_point: /
  time: 2013-01-03 18:21:56.863908 +09:00
  total_files: 983040
  total_size: 15853404160
  used_files: 501963
  used_size: 9731227648
- !ruby/object:RPerf::Resource::Filesystem 
  free_size: 776613888
  mount_point: /dev
  time: 2013-01-03 18:21:56.863922 +09:00
  total_files: 189604
  total_size: 776617984
  used_files: 451
  used_size: 4096
- !ruby/object:RPerf::Resource::Filesystem 
  free_size: 313647104
  mount_point: /run
  time: 2013-01-03 18:21:56.863930 +09:00
  total_files: 191923
  total_size: 314449920
  used_files: 366
  used_size: 802816
- !ruby/object:RPerf::Resource::Filesystem 
  free_size: 5242880
  mount_point: /run/lock
  time: 2013-01-03 18:21:56.863940 +09:00
  total_files: 191923
  total_size: 5242880
  used_files: 6
  used_size: 0
load_average: !ruby/object:RPerf::Resource::LoadAverage 
  la1: 0.42
  la15: 0.27
  la5: 0.36
  time: 2013-01-03 18:21:57.002372 +09:00
network_interfaces: 
- !ruby/object:RPerf::Resource::NetworkInterface 
  inbound_data_size: 1887498354
  inbound_error_count: 0
  inbound_packet_count: 1627865
  link_status: :up
  name: eth0
  outbound_data_size: 114445816
  outbound_error_count: 0
  outbound_packet_count: 878345
  time: 2013-01-03 18:21:56.733761 +09:00
- !ruby/object:RPerf::Resource::NetworkInterface 
  inbound_data_size: 1792258260
  inbound_error_count: 0
  inbound_packet_count: 508554
  link_status: :up
  name: lo
  outbound_data_size: 1792258260
  outbound_error_count: 0
  outbound_packet_count: 508554
  time: 2013-01-03 18:21:56.743136 +09:00
processes: 
- !ruby/object:RPerf::Resource::Process 
  argument: /sbin/init
  gid: 0
  parent_pid: 0
  pid: 1
  size: 
  start_time: 2012-12-29 20:58:44.828421 +09:00
  time: 2013-01-03 18:21:56.828421 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[kthreadd]"
  gid: 0
  parent_pid: 0
  pid: 2
  size: 
  start_time: 2012-12-29 20:58:44.828682 +09:00
  time: 2013-01-03 18:21:56.828682 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[ksoftirqd/0]"
  gid: 0
  parent_pid: 2
  pid: 3
  size: 
  start_time: 2012-12-29 20:58:44.828809 +09:00
  time: 2013-01-03 18:21:56.828809 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[migration/0]"
  gid: 0
  parent_pid: 2
  pid: 6
  size: 
  start_time: 2012-12-29 20:58:44.828962 +09:00
  time: 2013-01-03 18:21:56.828962 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[watchdog/0]"
  gid: 0
  parent_pid: 2
  pid: 7
  size: 
  start_time: 2012-12-29 20:58:44.829061 +09:00
  time: 2013-01-03 18:21:56.829061 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[migration/1]"
  gid: 0
  parent_pid: 2
  pid: 8
  size: 
  start_time: 2012-12-29 20:58:44.829150 +09:00
  time: 2013-01-03 18:21:56.829150 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[ksoftirqd/1]"
  gid: 0
  parent_pid: 2
  pid: 10
  size: 
  start_time: 2012-12-29 20:58:44.829248 +09:00
  time: 2013-01-03 18:21:56.829248 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[watchdog/1]"
  gid: 0
  parent_pid: 2
  pid: 12
  size: 
  start_time: 2012-12-29 20:58:44.829346 +09:00
  time: 2013-01-03 18:21:56.829346 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[cpuset]"
  gid: 0
  parent_pid: 2
  pid: 13
  size: 
  start_time: 2012-12-29 20:58:44.829578 +09:00
  time: 2013-01-03 18:21:56.829578 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[khelper]"
  gid: 0
  parent_pid: 2
  pid: 14
  size: 
  start_time: 2012-12-29 20:58:44.829701 +09:00
  time: 2013-01-03 18:21:56.829701 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[kdevtmpfs]"
  gid: 0
  parent_pid: 2
  pid: 15
  size: 
  start_time: 2012-12-29 20:58:44.829850 +09:00
  time: 2013-01-03 18:21:56.829850 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[netns]"
  gid: 0
  parent_pid: 2
  pid: 16
  size: 
  start_time: 2012-12-29 20:58:44.830012 +09:00
  time: 2013-01-03 18:21:56.830012 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[kworker/u:1]"
  gid: 0
  parent_pid: 2
  pid: 17
  size: 
  start_time: 2012-12-29 20:58:44.830120 +09:00
  time: 2013-01-03 18:21:56.830120 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[sync_supers]"
  gid: 0
  parent_pid: 2
  pid: 18
  size: 
  start_time: 2012-12-29 20:58:44.830212 +09:00
  time: 2013-01-03 18:21:56.830212 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[bdi-default]"
  gid: 0
  parent_pid: 2
  pid: 19
  size: 
  start_time: 2012-12-29 20:58:44.830303 +09:00
  time: 2013-01-03 18:21:56.830303 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[kintegrityd]"
  gid: 0
  parent_pid: 2
  pid: 20
  size: 
  start_time: 2012-12-29 20:58:44.830395 +09:00
  time: 2013-01-03 18:21:56.830395 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[kblockd]"
  gid: 0
  parent_pid: 2
  pid: 21
  size: 
  start_time: 2012-12-29 20:58:44.830481 +09:00
  time: 2013-01-03 18:21:56.830481 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[ata_sff]"
  gid: 0
  parent_pid: 2
  pid: 22
  size: 
  start_time: 2012-12-29 20:58:47.830637 +09:00
  time: 2013-01-03 18:21:56.830637 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[khubd]"
  gid: 0
  parent_pid: 2
  pid: 23
  size: 
  start_time: 2012-12-29 20:58:47.830730 +09:00
  time: 2013-01-03 18:21:56.830730 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[md]"
  gid: 0
  parent_pid: 2
  pid: 24
  size: 
  start_time: 2012-12-29 20:58:47.830932 +09:00
  time: 2013-01-03 18:21:56.830932 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[khungtaskd]"
  gid: 0
  parent_pid: 2
  pid: 26
  size: 
  start_time: 2012-12-29 20:58:50.831040 +09:00
  time: 2013-01-03 18:21:56.831040 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[kswapd0]"
  gid: 0
  parent_pid: 2
  pid: 27
  size: 
  start_time: 2012-12-29 20:58:50.831137 +09:00
  time: 2013-01-03 18:21:56.831137 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[ksmd]"
  gid: 0
  parent_pid: 2
  pid: 28
  size: 
  start_time: 2012-12-29 20:58:50.831224 +09:00
  time: 2013-01-03 18:21:56.831224 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[khugepaged]"
  gid: 0
  parent_pid: 2
  pid: 29
  size: 
  start_time: 2012-12-29 20:58:50.831317 +09:00
  time: 2013-01-03 18:21:56.831317 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[fsnotify_mark]"
  gid: 0
  parent_pid: 2
  pid: 30
  size: 
  start_time: 2012-12-29 20:58:50.831410 +09:00
  time: 2013-01-03 18:21:56.831410 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[ecryptfs-kthrea]"
  gid: 0
  parent_pid: 2
  pid: 31
  size: 
  start_time: 2012-12-29 20:58:50.831551 +09:00
  time: 2013-01-03 18:21:56.831551 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[crypto]"
  gid: 0
  parent_pid: 2
  pid: 32
  size: 
  start_time: 2012-12-29 20:58:50.831655 +09:00
  time: 2013-01-03 18:21:56.831655 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[kthrotld]"
  gid: 0
  parent_pid: 2
  pid: 40
  size: 
  start_time: 2012-12-29 20:58:50.831746 +09:00
  time: 2013-01-03 18:21:56.831746 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[scsi_eh_0]"
  gid: 0
  parent_pid: 2
  pid: 42
  size: 
  start_time: 2012-12-29 20:58:51.831918 +09:00
  time: 2013-01-03 18:21:56.831918 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[scsi_eh_1]"
  gid: 0
  parent_pid: 2
  pid: 43
  size: 
  start_time: 2012-12-29 20:58:51.832018 +09:00
  time: 2013-01-03 18:21:56.832018 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[devfreq_wq]"
  gid: 0
  parent_pid: 2
  pid: 63
  size: 
  start_time: 2012-12-29 20:58:51.832105 +09:00
  time: 2013-01-03 18:21:56.832105 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[kworker/1:2]"
  gid: 0
  parent_pid: 2
  pid: 108
  size: 
  start_time: 2012-12-29 20:58:51.832215 +09:00
  time: 2013-01-03 18:21:56.832215 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[mpt_poll_0]"
  gid: 0
  parent_pid: 2
  pid: 178
  size: 
  start_time: 2012-12-29 20:58:52.832308 +09:00
  time: 2013-01-03 18:21:56.832308 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[mpt/0]"
  gid: 0
  parent_pid: 2
  pid: 179
  size: 
  start_time: 2012-12-29 20:58:52.832397 +09:00
  time: 2013-01-03 18:21:56.832397 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[scsi_eh_2]"
  gid: 0
  parent_pid: 2
  pid: 261
  size: 
  start_time: 2012-12-29 20:58:52.832547 +09:00
  time: 2013-01-03 18:21:56.832547 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[kjournald]"
  gid: 0
  parent_pid: 2
  pid: 277
  size: 
  start_time: 2012-12-29 20:58:57.832657 +09:00
  time: 2013-01-03 18:21:56.832657 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: upstart-udev-bridge --daemon
  gid: 0
  parent_pid: 1
  pid: 487
  size: 
  start_time: 2012-12-29 20:58:59.832745 +09:00
  time: 2013-01-03 18:21:56.832745 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /sbin/udevd --daemon
  gid: 0
  parent_pid: 1
  pid: 490
  size: 
  start_time: 2012-12-29 20:58:59.832919 +09:00
  time: 2013-01-03 18:21:56.832919 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[ttm_swap]"
  gid: 0
  parent_pid: 2
  pid: 560
  size: 
  start_time: 2012-12-29 20:59:00.833019 +09:00
  time: 2013-01-03 18:21:56.833019 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[rpciod]"
  gid: 0
  parent_pid: 2
  pid: 612
  size: 
  start_time: 2012-12-29 20:59:00.833106 +09:00
  time: 2013-01-03 18:21:56.833106 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[nfsiod]"
  gid: 0
  parent_pid: 2
  pid: 623
  size: 
  start_time: 2012-12-29 20:59:00.833199 +09:00
  time: 2013-01-03 18:21:56.833199 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[kpsmoused]"
  gid: 0
  parent_pid: 2
  pid: 673
  size: 
  start_time: 2012-12-29 20:59:00.833290 +09:00
  time: 2013-01-03 18:21:56.833290 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: rpc.idmapd
  gid: 0
  parent_pid: 1
  pid: 709
  size: 
  start_time: 2012-12-29 20:59:00.833381 +09:00
  time: 2013-01-03 18:21:56.833381 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: rsyslogd -c5
  gid: 103
  parent_pid: 1
  pid: 717
  size: 
  start_time: 2012-12-29 20:59:00.833479 +09:00
  time: 2013-01-03 18:21:56.833479 +09:00
  uid: 101
- !ruby/object:RPerf::Resource::Process 
  argument: dbus-daemon --system --fork --activation=upstart
  gid: 107
  parent_pid: 1
  pid: 735
  size: 
  start_time: 2012-12-29 20:59:00.833629 +09:00
  time: 2013-01-03 18:21:56.833629 +09:00
  uid: 103
- !ruby/object:RPerf::Resource::Process 
  argument: upstart-socket-bridge --daemon
  gid: 0
  parent_pid: 1
  pid: 791
  size: 
  start_time: 2012-12-29 20:59:01.833725 +09:00
  time: 2013-01-03 18:21:56.833725 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: rpcbind -w
  gid: 0
  parent_pid: 1
  pid: 794
  size: 
  start_time: 2012-12-29 20:59:01.833887 +09:00
  time: 2013-01-03 18:21:56.833887 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/sbin/cupsd -F
  gid: 0
  parent_pid: 1
  pid: 804
  size: 
  start_time: 2012-12-29 20:59:01.833990 +09:00
  time: 2013-01-03 18:21:56.833990 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/sbin/bluetoothd
  gid: 0
  parent_pid: 1
  pid: 817
  size: 
  start_time: 2012-12-29 20:59:01.834084 +09:00
  time: 2013-01-03 18:21:56.834084 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: rpc.statd -L
  gid: 0
  parent_pid: 1
  pid: 823
  size: 
  start_time: 2012-12-29 20:59:01.834180 +09:00
  time: 2013-01-03 18:21:56.834180 +09:00
  uid: 117
- !ruby/object:RPerf::Resource::Process 
  argument: "avahi-daemon: running [mobile02.local]"
  gid: 113
  parent_pid: 1
  pid: 825
  size: 
  start_time: 2012-12-29 20:59:01.834269 +09:00
  time: 2013-01-03 18:21:56.834269 +09:00
  uid: 106
- !ruby/object:RPerf::Resource::Process 
  argument: "avahi-daemon: chroot helper"
  gid: 113
  parent_pid: 825
  pid: 826
  size: 
  start_time: 2012-12-29 20:59:01.834364 +09:00
  time: 2013-01-03 18:21:56.834364 +09:00
  uid: 106
- !ruby/object:RPerf::Resource::Process 
  argument: "[krfcommd]"
  gid: 0
  parent_pid: 2
  pid: 836
  size: 
  start_time: 2012-12-29 20:59:01.834455 +09:00
  time: 2013-01-03 18:21:56.834455 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/sbin/modem-manager
  gid: 0
  parent_pid: 1
  pid: 853
  size: 
  start_time: 2012-12-29 20:59:01.834619 +09:00
  time: 2013-01-03 18:21:56.834619 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: NetworkManager
  gid: 0
  parent_pid: 1
  pid: 890
  size: 
  start_time: 2012-12-29 20:59:01.834715 +09:00
  time: 2013-01-03 18:21:56.834715 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/policykit-1/polkitd --no-debug
  gid: 0
  parent_pid: 1
  pid: 916
  size: 
  start_time: 2012-12-29 20:59:01.834962 +09:00
  time: 2013-01-03 18:21:56.834962 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /sbin/dhclient -d -4 -sf /usr/lib/NetworkManager/nm-dhcp-client.action -pf /var/run/sendsigs.omit.d/network-manager.dhclient-eth0.pid -lf /var/lib/dhcp/dhclient-8858ecc0-0455-4cf9-baa4-4b3ae39ab495-eth0.lease -cf /var/run/nm-dhclient-eth0.conf eth0
  gid: 0
  parent_pid: 890
  pid: 925
  size: 
  start_time: 2012-12-29 20:59:01.835090 +09:00
  time: 2013-01-03 18:21:56.835090 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "runsvdir -P /etc/service log: ..........................................................................................................................................................................................................................................................................................................................................................................................................."
  gid: 0
  parent_pid: 1
  pid: 957
  size: 
  start_time: 2012-12-29 20:59:01.835285 +09:00
  time: 2013-01-03 18:21:56.835285 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /sbin/getty -8 38400 tty4
  gid: 0
  parent_pid: 1
  pid: 960
  size: 
  start_time: 2012-12-29 20:59:01.835376 +09:00
  time: 2013-01-03 18:21:56.835376 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: runsv git-daemon
  gid: 0
  parent_pid: 957
  pid: 961
  size: 
  start_time: 2012-12-29 20:59:01.835456 +09:00
  time: 2013-01-03 18:21:56.835456 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: svlogd -tt /var/log/git-daemon
  gid: 65534
  parent_pid: 961
  pid: 965
  size: 
  start_time: 2012-12-29 20:59:01.835604 +09:00
  time: 2013-01-03 18:21:56.835604 +09:00
  uid: 118
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/git-core/git-daemon --verbose --reuseaddr --base-path=/var/cache /var/cache/git
  gid: 65534
  parent_pid: 961
  pid: 966
  size: 
  start_time: 2012-12-29 20:59:01.835689 +09:00
  time: 2013-01-03 18:21:56.835689 +09:00
  uid: 119
- !ruby/object:RPerf::Resource::Process 
  argument: /sbin/getty -8 38400 tty5
  gid: 0
  parent_pid: 1
  pid: 973
  size: 
  start_time: 2012-12-29 20:59:01.835802 +09:00
  time: 2013-01-03 18:21:56.835802 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /sbin/getty -8 38400 tty2
  gid: 0
  parent_pid: 1
  pid: 992
  size: 
  start_time: 2012-12-29 20:59:02.835950 +09:00
  time: 2013-01-03 18:21:56.835950 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /sbin/getty -8 38400 tty3
  gid: 0
  parent_pid: 1
  pid: 993
  size: 
  start_time: 2012-12-29 20:59:02.837241 +09:00
  time: 2013-01-03 18:21:56.837241 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /sbin/getty -8 38400 tty6
  gid: 0
  parent_pid: 1
  pid: 995
  size: 
  start_time: 2012-12-29 20:59:02.837418 +09:00
  time: 2013-01-03 18:21:56.837418 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: acpid -c /etc/acpi/events -s /var/run/acpid.socket
  gid: 0
  parent_pid: 1
  pid: 1004
  size: 
  start_time: 2012-12-29 20:59:02.837514 +09:00
  time: 2013-01-03 18:21:56.837514 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: cron
  gid: 0
  parent_pid: 1
  pid: 1005
  size: 
  start_time: 2012-12-29 20:59:02.837597 +09:00
  time: 2013-01-03 18:21:56.837597 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: atd
  gid: 1
  parent_pid: 1
  pid: 1006
  size: 
  start_time: 2012-12-29 20:59:02.837687 +09:00
  time: 2013-01-03 18:21:56.837687 +09:00
  uid: 1
- !ruby/object:RPerf::Resource::Process 
  argument: lightdm
  gid: 0
  parent_pid: 1
  pid: 1022
  size: 
  start_time: 2012-12-29 20:59:02.838059 +09:00
  time: 2013-01-03 18:21:56.838059 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/sbin/irqbalance
  gid: 0
  parent_pid: 1
  pid: 1042
  size: 
  start_time: 2012-12-29 20:59:02.838247 +09:00
  time: 2013-01-03 18:21:56.838247 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/X :0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch -background none
  gid: 0
  parent_pid: 1022
  pid: 1045
  size: 
  start_time: 2012-12-29 20:59:02.838399 +09:00
  time: 2013-01-03 18:21:56.838399 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: whoopsie
  gid: 128
  parent_pid: 1
  pid: 1047
  size: 
  start_time: 2012-12-29 20:59:02.838608 +09:00
  time: 2013-01-03 18:21:56.838608 +09:00
  uid: 116
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/postfix/master
  gid: 0
  parent_pid: 1
  pid: 1184
  size: 
  start_time: 2012-12-29 20:59:02.838718 +09:00
  time: 2013-01-03 18:21:56.838718 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/sbin/vmtoolsd
  gid: 0
  parent_pid: 1
  pid: 1226
  size: 
  start_time: 2012-12-29 20:59:03.838918 +09:00
  time: 2013-01-03 18:21:56.838918 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: lightdm --session-child 12 15
  gid: 0
  parent_pid: 1022
  pid: 1247
  size: 
  start_time: 2012-12-29 20:59:03.839018 +09:00
  time: 2013-01-03 18:21:56.839018 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /sbin/mdadm --monitor --pid-file /var/run/mdadm/monitor.pid --daemonise --scan --syslog
  gid: 0
  parent_pid: 1
  pid: 1278
  size: 
  start_time: 2012-12-29 20:59:03.839115 +09:00
  time: 2013-01-03 18:21:56.839115 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/accountsservice/accounts-daemon
  gid: 0
  parent_pid: 1
  pid: 1285
  size: 
  start_time: 2012-12-29 20:59:03.839209 +09:00
  time: 2013-01-03 18:21:56.839209 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/sbin/console-kit-daemon --no-daemon
  gid: 0
  parent_pid: 1
  pid: 1318
  size: 
  start_time: 2012-12-29 20:59:03.839297 +09:00
  time: 2013-01-03 18:21:56.839297 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: gnome-session --session=ubuntu
  gid: 1000
  parent_pid: 1247
  pid: 1437
  size: 
  start_time: 2012-12-29 20:59:04.839414 +09:00
  time: 2013-01-03 18:21:56.839414 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/sbin/apache2 -k start
  gid: 0
  parent_pid: 1
  pid: 1438
  size: 
  start_time: 2012-12-29 20:59:04.839563 +09:00
  time: 2013-01-03 18:21:56.839563 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[flush-8:0]"
  gid: 0
  parent_pid: 2
  pid: 1682
  size: 
  start_time: 2012-12-29 20:59:05.839659 +09:00
  time: 2013-01-03 18:21:56.839659 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /sbin/getty -8 38400 tty1
  gid: 0
  parent_pid: 1
  pid: 1726
  size: 
  start_time: 2012-12-29 20:59:05.839754 +09:00
  time: 2013-01-03 18:21:56.839754 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[lightdm-session] <defunct>"
  gid: 1000
  parent_pid: 1437
  pid: 1728
  size: 
  start_time: 2012-12-29 20:59:05.839983 +09:00
  time: 2013-01-03 18:21:56.839983 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/ssh-agent /usr/bin/dbus-launch --exit-with-session gnome-session --session=ubuntu
  gid: 1000
  parent_pid: 1437
  pid: 1737
  size: 
  start_time: 2012-12-29 20:59:05.840083 +09:00
  time: 2013-01-03 18:21:56.840083 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/dbus-launch --exit-with-session gnome-session --session=ubuntu
  gid: 1000
  parent_pid: 1
  pid: 1740
  size: 
  start_time: 2012-12-29 20:59:05.840180 +09:00
  time: 2013-01-03 18:21:56.840180 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: //bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
  gid: 1000
  parent_pid: 1
  pid: 1741
  size: 
  start_time: 2012-12-29 20:59:06.840273 +09:00
  time: 2013-01-03 18:21:56.840273 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/gvfs/gvfsd
  gid: 1000
  parent_pid: 1
  pid: 1745
  size: 
  start_time: 2012-12-29 20:59:06.840360 +09:00
  time: 2013-01-03 18:21:56.840360 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/gvfs//gvfs-fuse-daemon -f /home/toshi/.gvfs
  gid: 1000
  parent_pid: 1
  pid: 1747
  size: 
  start_time: 2012-12-29 20:59:06.840455 +09:00
  time: 2013-01-03 18:21:56.840455 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/gnome-settings-daemon/gnome-settings-daemon
  gid: 1000
  parent_pid: 1437
  pid: 1762
  size: 
  start_time: 2012-12-29 20:59:06.840605 +09:00
  time: 2013-01-03 18:21:56.840605 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/gnome-keyring-daemon --start --components=secrets
  gid: 1000
  parent_pid: 1
  pid: 1763
  size: 
  start_time: 2012-12-29 20:59:06.840703 +09:00
  time: 2013-01-03 18:21:56.840703 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/upower/upowerd
  gid: 0
  parent_pid: 1
  pid: 1773
  size: 
  start_time: 2012-12-29 20:59:07.840856 +09:00
  time: 2013-01-03 18:21:56.840856 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: metacity
  gid: 1000
  parent_pid: 1437
  pid: 1932
  size: 
  start_time: 2012-12-29 20:59:07.840984 +09:00
  time: 2013-01-03 18:21:56.840984 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/x86_64-linux-gnu/colord/colord
  gid: 105
  parent_pid: 1
  pid: 1934
  size: 
  start_time: 2012-12-29 20:59:07.841080 +09:00
  time: 2013-01-03 18:21:56.841080 +09:00
  uid: 102
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/x86_64-linux-gnu/gconf/gconfd-2
  gid: 1000
  parent_pid: 1
  pid: 1941
  size: 
  start_time: 2012-12-29 20:59:07.841174 +09:00
  time: 2013-01-03 18:21:56.841174 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: unity-2d-panel
  gid: 1000
  parent_pid: 1437
  pid: 1943
  size: 
  start_time: 2012-12-29 20:59:08.841261 +09:00
  time: 2013-01-03 18:21:56.841261 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: unity-2d-shell
  gid: 1000
  parent_pid: 1437
  pid: 1944
  size: 
  start_time: 2012-12-29 20:59:08.841354 +09:00
  time: 2013-01-03 18:21:56.841354 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/pulseaudio --start --log-target=syslog
  gid: 1000
  parent_pid: 1
  pid: 1947
  size: 
  start_time: 2012-12-29 20:59:08.841448 +09:00
  time: 2013-01-03 18:21:56.841448 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/rtkit/rtkit-daemon
  gid: 122
  parent_pid: 1
  pid: 1949
  size: 
  start_time: 2012-12-29 20:59:08.841595 +09:00
  time: 2013-01-03 18:21:56.841595 +09:00
  uid: 110
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/pulseaudio/pulse/gconf-helper
  gid: 1000
  parent_pid: 1947
  pid: 1958
  size: 
  start_time: 2012-12-29 20:59:09.841700 +09:00
  time: 2013-01-03 18:21:56.841700 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: bluetooth-applet
  gid: 1000
  parent_pid: 1437
  pid: 1959
  size: 
  start_time: 2012-12-29 20:59:09.841862 +09:00
  time: 2013-01-03 18:21:56.841862 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: nautilus -n
  gid: 1000
  parent_pid: 1437
  pid: 1961
  size: 
  start_time: 2012-12-29 20:59:09.842015 +09:00
  time: 2013-01-03 18:21:56.842015 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/gnome-settings-daemon/gnome-fallback-mount-helper
  gid: 1000
  parent_pid: 1437
  pid: 1962
  size: 
  start_time: 2012-12-29 20:59:09.842114 +09:00
  time: 2013-01-03 18:21:56.842114 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
  gid: 1000
  parent_pid: 1437
  pid: 1963
  size: 
  start_time: 2012-12-29 20:59:09.842209 +09:00
  time: 2013-01-03 18:21:56.842209 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: nm-applet
  gid: 1000
  parent_pid: 1437
  pid: 1969
  size: 
  start_time: 2012-12-29 20:59:09.842296 +09:00
  time: 2013-01-03 18:21:56.842296 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/vmware-tools/bin64/vmware-user-loader
  gid: 1000
  parent_pid: 1
  pid: 1970
  size: 
  start_time: 2012-12-29 20:59:09.842391 +09:00
  time: 2013-01-03 18:21:56.842391 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/bamf/bamfdaemon
  gid: 1000
  parent_pid: 1
  pid: 1974
  size: 
  start_time: 2012-12-29 20:59:09.842484 +09:00
  time: 2013-01-03 18:21:56.842484 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/gvfs/gvfs-gdu-volume-monitor
  gid: 1000
  parent_pid: 1
  pid: 1987
  size: 
  start_time: 2012-12-29 20:59:09.842641 +09:00
  time: 2013-01-03 18:21:56.842641 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/udisks/udisks-daemon
  gid: 0
  parent_pid: 1
  pid: 1992
  size: 
  start_time: 2012-12-29 20:59:09.842735 +09:00
  time: 2013-01-03 18:21:56.842735 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "udisks-daemon: not polling any devices"
  gid: 0
  parent_pid: 1992
  pid: 1993
  size: 
  start_time: 2012-12-29 20:59:10.842927 +09:00
  time: 2013-01-03 18:21:56.842927 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/gvfs/gvfs-gphoto2-volume-monitor
  gid: 1000
  parent_pid: 1
  pid: 1997
  size: 
  start_time: 2012-12-29 20:59:10.843032 +09:00
  time: 2013-01-03 18:21:56.843032 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/gvfs/gvfs-afc-volume-monitor
  gid: 1000
  parent_pid: 1
  pid: 1999
  size: 
  start_time: 2012-12-29 20:59:10.843126 +09:00
  time: 2013-01-03 18:21:56.843126 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/gvfs/gvfsd-trash --spawner :1.2 /org/gtk/gvfs/exec_spaw/0
  gid: 1000
  parent_pid: 1
  pid: 2002
  size: 
  start_time: 2012-12-29 20:59:10.843217 +09:00
  time: 2013-01-03 18:21:56.843217 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/dconf/dconf-service
  gid: 1000
  parent_pid: 1
  pid: 2005
  size: 
  start_time: 2012-12-29 20:59:10.843319 +09:00
  time: 2013-01-03 18:21:56.843319 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/unity/unity-panel-service
  gid: 1000
  parent_pid: 1
  pid: 2021
  size: 
  start_time: 2012-12-29 20:59:10.843412 +09:00
  time: 2013-01-03 18:21:56.843412 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/indicator-datetime/indicator-datetime-service
  gid: 1000
  parent_pid: 1
  pid: 2027
  size: 
  start_time: 2012-12-29 20:59:11.843555 +09:00
  time: 2013-01-03 18:21:56.843555 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/indicator-application/indicator-application-service
  gid: 1000
  parent_pid: 1
  pid: 2030
  size: 
  start_time: 2012-12-29 20:59:11.843660 +09:00
  time: 2013-01-03 18:21:56.843660 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/indicator-printers/indicator-printers-service
  gid: 1000
  parent_pid: 1
  pid: 2033
  size: 
  start_time: 2012-12-29 20:59:11.843756 +09:00
  time: 2013-01-03 18:21:56.843756 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/indicator-messages/indicator-messages-service
  gid: 1000
  parent_pid: 1
  pid: 2034
  size: 
  start_time: 2012-12-29 20:59:11.843932 +09:00
  time: 2013-01-03 18:21:56.843932 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/indicator-session/indicator-session-service
  gid: 1000
  parent_pid: 1
  pid: 2035
  size: 
  start_time: 2012-12-29 20:59:11.844034 +09:00
  time: 2013-01-03 18:21:56.844034 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/indicator-sound/indicator-sound-service
  gid: 1000
  parent_pid: 1
  pid: 2037
  size: 
  start_time: 2012-12-29 20:59:11.851410 +09:00
  time: 2013-01-03 18:21:56.851410 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/gvfs/gvfsd-burn --spawner :1.2 /org/gtk/gvfs/exec_spaw/1
  gid: 1000
  parent_pid: 1
  pid: 2056
  size: 
  start_time: 2012-12-29 20:59:11.851561 +09:00
  time: 2013-01-03 18:21:56.851561 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/geoclue/geoclue-master
  gid: 1000
  parent_pid: 1
  pid: 2074
  size: 
  start_time: 2012-12-29 20:59:11.851611 +09:00
  time: 2013-01-03 18:21:56.851611 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/ubuntu-geoip/ubuntu-geoip-provider
  gid: 1000
  parent_pid: 1
  pid: 2091
  size: 
  start_time: 2012-12-29 20:59:12.851670 +09:00
  time: 2013-01-03 18:21:56.851670 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/gnome-online-accounts/goa-daemon
  gid: 1000
  parent_pid: 1
  pid: 2097
  size: 
  start_time: 2012-12-29 20:59:13.851718 +09:00
  time: 2013-01-03 18:21:56.851718 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/indicator-appmenu/hud-service
  gid: 1000
  parent_pid: 1
  pid: 2110
  size: 
  start_time: 2012-12-29 20:59:13.851765 +09:00
  time: 2013-01-03 18:21:56.851765 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/unity-lens-applications/unity-applications-daemon
  gid: 1000
  parent_pid: 1
  pid: 2113
  size: 
  start_time: 2012-12-29 20:59:13.851864 +09:00
  time: 2013-01-03 18:21:56.851864 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/unity-lens-files/unity-files-daemon
  gid: 1000
  parent_pid: 1
  pid: 2116
  size: 
  start_time: 2012-12-29 20:59:13.851926 +09:00
  time: 2013-01-03 18:21:56.851926 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/unity-lens-music/unity-music-daemon
  gid: 1000
  parent_pid: 1
  pid: 2118
  size: 
  start_time: 2012-12-29 20:59:13.851975 +09:00
  time: 2013-01-03 18:21:56.851975 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/python /usr/lib/unity-lens-video/unity-lens-video
  gid: 1000
  parent_pid: 1
  pid: 2119
  size: 
  start_time: 2012-12-29 20:59:13.852019 +09:00
  time: 2013-01-03 18:21:56.852019 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/zeitgeist-daemon
  gid: 1000
  parent_pid: 1
  pid: 2153
  size: 
  start_time: 2012-12-29 20:59:14.852065 +09:00
  time: 2013-01-03 18:21:56.852065 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: zeitgeist-datahub
  gid: 1000
  parent_pid: 1
  pid: 2162
  size: 
  start_time: 2012-12-29 20:59:14.852111 +09:00
  time: 2013-01-03 18:21:56.852111 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/zeitgeist/zeitgeist-fts
  gid: 1000
  parent_pid: 1
  pid: 2163
  size: 
  start_time: 2012-12-29 20:59:14.852154 +09:00
  time: 2013-01-03 18:21:56.852154 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /bin/cat
  gid: 1000
  parent_pid: 2163
  pid: 2179
  size: 
  start_time: 2012-12-29 20:59:14.852200 +09:00
  time: 2013-01-03 18:21:56.852200 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: qmgr -l -t fifo -u
  gid: 126
  parent_pid: 1184
  pid: 2211
  size: 
  start_time: 2012-12-29 20:59:14.852243 +09:00
  time: 2013-01-03 18:21:56.852243 +09:00
  uid: 115
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/ibus-daemon --xim
  gid: 1000
  parent_pid: 1
  pid: 2245
  size: 
  start_time: 2012-12-29 20:59:15.852293 +09:00
  time: 2013-01-03 18:21:56.852293 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/x86_64-linux-gnu/ibus/ibus-gconf
  gid: 1000
  parent_pid: 2245
  pid: 2246
  size: 
  start_time: 2012-12-29 20:59:15.852340 +09:00
  time: 2013-01-03 18:21:56.852340 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/python /usr/share/ibus/ui/gtk/main.py
  gid: 1000
  parent_pid: 2245
  pid: 2248
  size: 
  start_time: 2012-12-29 20:59:15.852383 +09:00
  time: 2013-01-03 18:21:56.852383 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/x86_64-linux-gnu/ibus/ibus-x11 --kill-daemon
  gid: 1000
  parent_pid: 1
  pid: 2250
  size: 
  start_time: 2012-12-29 20:59:15.852430 +09:00
  time: 2013-01-03 18:21:56.852430 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/ibus-mozc/ibus-engine-mozc --ibus
  gid: 1000
  parent_pid: 2245
  pid: 2258
  size: 
  start_time: 2012-12-29 20:59:15.852476 +09:00
  time: 2013-01-03 18:21:56.852476 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/notify-osd/notify-osd
  gid: 1000
  parent_pid: 1
  pid: 2265
  size: 
  start_time: 2012-12-29 20:59:16.852556 +09:00
  time: 2013-01-03 18:21:56.852556 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/python /usr/lib/unity-scope-video-remote/unity-scope-video-remote
  gid: 1000
  parent_pid: 1
  pid: 2269
  size: 
  start_time: 2012-12-29 20:59:16.852605 +09:00
  time: 2013-01-03 18:21:56.852605 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/unity-lens-music/unity-musicstore-daemon
  gid: 1000
  parent_pid: 1
  pid: 2271
  size: 
  start_time: 2012-12-29 20:59:16.852651 +09:00
  time: 2013-01-03 18:21:56.852651 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/gnome-disk-utility/gdu-notification-daemon
  gid: 1000
  parent_pid: 1437
  pid: 2297
  size: 
  start_time: 2012-12-29 20:59:19.852697 +09:00
  time: 2013-01-03 18:21:56.852697 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: telepathy-indicator
  gid: 1000
  parent_pid: 1437
  pid: 2302
  size: 
  start_time: 2012-12-29 20:59:24.852743 +09:00
  time: 2013-01-03 18:21:56.852743 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/telepathy/mission-control-5
  gid: 1000
  parent_pid: 1
  pid: 2309
  size: 
  start_time: 2012-12-29 20:59:24.852841 +09:00
  time: 2013-01-03 18:21:56.852841 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: gnome-screensaver
  gid: 1000
  parent_pid: 1437
  pid: 2365
  size: 
  start_time: 2012-12-29 20:59:29.852904 +09:00
  time: 2013-01-03 18:21:56.852904 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 114:125
  gid: 125
  parent_pid: 1
  pid: 2399
  size: 
  start_time: 2012-12-29 20:59:38.852962 +09:00
  time: 2013-01-03 18:21:56.852962 +09:00
  uid: 114
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/evolution/3.2/evolution-alarm-notify
  gid: 1000
  parent_pid: 1437
  pid: 2402
  size: 
  start_time: 2012-12-29 20:59:39.853042 +09:00
  time: 2013-01-03 18:21:56.853042 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/evolution/e-calendar-factory
  gid: 1000
  parent_pid: 1
  pid: 2406
  size: 
  start_time: 2012-12-29 20:59:40.853118 +09:00
  time: 2013-01-03 18:21:56.853118 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/evolution/e-addressbook-factory
  gid: 1000
  parent_pid: 1
  pid: 2413
  size: 
  start_time: 2012-12-29 20:59:40.853212 +09:00
  time: 2013-01-03 18:21:56.853212 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: update-notifier
  gid: 1000
  parent_pid: 1437
  pid: 2434
  size: 
  start_time: 2012-12-29 21:00:09.853306 +09:00
  time: 2013-01-03 18:21:56.853306 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: gnome-terminal
  gid: 1000
  parent_pid: 1
  pid: 2466
  size: 
  start_time: 2012-12-29 21:00:57.853398 +09:00
  time: 2013-01-03 18:21:56.853398 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: gnome-pty-helper
  gid: 43
  parent_pid: 2466
  pid: 2473
  size: 
  start_time: 2012-12-29 21:00:58.853482 +09:00
  time: 2013-01-03 18:21:56.853482 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: bash
  gid: 1000
  parent_pid: 2466
  pid: 2474
  size: 
  start_time: 2012-12-29 21:00:58.853588 +09:00
  time: 2013-01-03 18:21:56.853588 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/deja-dup/deja-dup/deja-dup-monitor
  gid: 1000
  parent_pid: 1437
  pid: 2534
  size: 
  start_time: 2012-12-29 21:01:09.853660 +09:00
  time: 2013-01-03 18:21:56.853660 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/python /usr/lib/system-service/system-service-d
  gid: 0
  parent_pid: 1
  pid: 2589
  size: 
  start_time: 2012-12-29 21:02:31.853728 +09:00
  time: 2013-01-03 18:21:56.853728 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/at-spi2-core/at-spi-bus-launcher
  gid: 1000
  parent_pid: 1
  pid: 2706
  size: 
  start_time: 2012-12-29 21:02:44.853814 +09:00
  time: 2013-01-03 18:21:56.853814 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: emacs test/test_targetsconfig.rb
  gid: 1000
  parent_pid: 2474
  pid: 3341
  size: 
  start_time: 2013-01-02 09:56:48.853875 +09:00
  time: 2013-01-03 18:21:56.853875 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /bin/bash
  gid: 1000
  parent_pid: 3341
  pid: 3351
  size: 
  start_time: 2013-01-02 09:56:58.853923 +09:00
  time: 2013-01-03 18:21:56.853923 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/gvfs/gvfsd-metadata
  gid: 1000
  parent_pid: 1
  pid: 3403
  size: 
  start_time: 2012-12-29 21:03:39.853969 +09:00
  time: 2013-01-03 18:21:56.853969 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: jd
  gid: 1000
  parent_pid: 1
  pid: 3677
  size: 
  start_time: 2013-01-02 10:48:31.854018 +09:00
  time: 2013-01-03 18:21:56.854018 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/python2.7 /usr/bin/everpad
  gid: 1000
  parent_pid: 2474
  pid: 4494
  size: 
  start_time: 2012-12-29 21:06:07.854066 +09:00
  time: 2013-01-03 18:21:56.854066 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/python2.7 /usr/bin/everpad-provider
  gid: 1000
  parent_pid: 1
  pid: 4503
  size: 
  start_time: 2012-12-29 21:06:08.854115 +09:00
  time: 2013-01-03 18:21:56.854115 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: bash
  gid: 1000
  parent_pid: 2466
  pid: 4913
  size: 
  start_time: 2012-12-29 22:08:35.854166 +09:00
  time: 2013-01-03 18:21:56.854166 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/gnome-settings-daemon/gsd-locate-pointer
  gid: 1000
  parent_pid: 1
  pid: 6019
  size: 
  start_time: 2013-01-02 16:34:23.854211 +09:00
  time: 2013-01-03 18:21:56.854211 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/sbin/apache2 -k start
  gid: 33
  parent_pid: 1438
  pid: 10614
  size: 
  start_time: 2012-12-30 08:26:21.854261 +09:00
  time: 2013-01-03 18:21:56.854261 +09:00
  uid: 33
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/sbin/apache2 -k start
  gid: 33
  parent_pid: 1438
  pid: 10615
  size: 
  start_time: 2012-12-30 08:26:21.854318 +09:00
  time: 2013-01-03 18:21:56.854318 +09:00
  uid: 33
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/sbin/apache2 -k start
  gid: 33
  parent_pid: 1438
  pid: 10649
  size: 
  start_time: 2012-12-30 08:26:22.854364 +09:00
  time: 2013-01-03 18:21:56.854364 +09:00
  uid: 33
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/mozc_emacs_helper --suppress_stderr
  gid: 1000
  parent_pid: 3341
  pid: 12812
  size: 
  start_time: 2013-01-03 11:45:49.854425 +09:00
  time: 2013-01-03 18:21:56.854425 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: "[kworker/0:2]"
  gid: 0
  parent_pid: 2
  pid: 14715
  size: 
  start_time: 2013-01-03 16:32:49.854475 +09:00
  time: 2013-01-03 18:21:56.854475 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: pickup -l -t fifo -u -c
  gid: 126
  parent_pid: 1184
  pid: 15754
  size: 
  start_time: 2013-01-03 18:08:56.854573 +09:00
  time: 2013-01-03 18:21:56.854573 +09:00
  uid: 115
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/python /usr/share/oneconf/oneconf-service
  gid: 1000
  parent_pid: 1
  pid: 15866
  size: 
  start_time: 2013-01-03 18:12:37.854625 +09:00
  time: 2013-01-03 18:21:56.854625 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: "[kworker/0:0]"
  gid: 0
  parent_pid: 2
  pid: 16884
  size: 
  start_time: 2013-01-03 18:13:12.854675 +09:00
  time: 2013-01-03 18:21:56.854675 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[kworker/0:1]"
  gid: 0
  parent_pid: 2
  pid: 16928
  size: 
  start_time: 2013-01-03 18:18:13.854721 +09:00
  time: 2013-01-03 18:21:56.854721 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: sudo /usr/bin/rperfagent
  gid: 1000
  parent_pid: 4913
  pid: 17176
  size: 
  start_time: 2013-01-03 18:21:30.854771 +09:00
  time: 2013-01-03 18:21:56.854771 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/ruby1.8 /usr/bin/rperfagent
  gid: 0
  parent_pid: 17176
  pid: 17177
  size: 
  start_time: 2013-01-03 18:21:30.854886 +09:00
  time: 2013-01-03 18:21:56.854886 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: wget http://localhost:20080/resource
  gid: 1000
  parent_pid: 2474
  pid: 17183
  size: 
  start_time: 2013-01-03 18:21:56.854938 +09:00
  time: 2013-01-03 18:21:56.854938 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /bin/ps -e --no-header -o pid,ppid,uid,gid,etime,args
  gid: 0
  parent_pid: 17177
  pid: 17191
  size: 
  start_time: 2013-01-03 18:21:56.855592 +09:00
  time: 2013-01-03 18:21:56.855592 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[kworker/u:2]"
  gid: 0
  parent_pid: 2
  pid: 22565
  size: 
  start_time: 2012-12-31 14:25:25.855642 +09:00
  time: 2013-01-03 18:21:56.855642 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: "[kworker/1:0]"
  gid: 0
  parent_pid: 2
  pid: 22567
  size: 
  start_time: 2012-12-31 14:25:25.855694 +09:00
  time: 2013-01-03 18:21:56.855694 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /sbin/udevd --daemon
  gid: 0
  parent_pid: 490
  pid: 22620
  size: 
  start_time: 2012-12-31 14:26:41.855743 +09:00
  time: 2013-01-03 18:21:56.855743 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /sbin/udevd --daemon
  gid: 0
  parent_pid: 490
  pid: 22625
  size: 
  start_time: 2012-12-31 14:26:41.855863 +09:00
  time: 2013-01-03 18:21:56.855863 +09:00
  uid: 0
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/sbin/dnsmasq --no-resolv --keep-in-foreground --no-hosts --bind-interfaces --pid-file=/var/run/sendsigs.omit.d/network-manager.dnsmasq.pid --listen-address=127.0.0.1 --conf-file=/var/run/nm-dns-dnsmasq.conf --cache-size=0 --proxy-dnssec
  gid: 30
  parent_pid: 890
  pid: 30348
  size: 
  start_time: 2013-01-01 21:08:35.855960 +09:00
  time: 2013-01-03 18:21:56.855960 +09:00
  uid: 65534
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/lib/mozc/mozc_server
  gid: 1000
  parent_pid: 2258
  pid: 31122
  size: 
  start_time: 2013-01-01 22:26:06.856005 +09:00
  time: 2013-01-03 18:21:56.856005 +09:00
  uid: 1000
- !ruby/object:RPerf::Resource::Process 
  argument: /usr/bin/unity-2d-spread
  gid: 1000
  parent_pid: 1
  pid: 31486
  size: 
  start_time: 2013-01-01 22:46:49.856052 +09:00
  time: 2013-01-03 18:21:56.856052 +09:00
  uid: 1000
virtual_memory: !ruby/object:RPerf::Resource::VirtualMemory 
  buffer_memory: 34852864
  cache_memory: 508624896
  time: 2013-01-03 18:21:56.671601 +09:00
  total_memory: 1572237312
  total_swap: 2146430976
  used_memory: 1474584576
  used_swap: 302288896
