# -*- coding: utf-8 -*-

require 'rocuses/utils'
require 'rocuses/graphtemplate/cpu'
require 'rocuses/graphtemplate/cpuaverage'
require 'rocuses/graphtemplate/loadaverage'
require 'rocuses/graphtemplate/loadaveragemax'
require 'rocuses/graphtemplate/memory'
require 'rocuses/graphtemplate/swap'
require 'rocuses/graphtemplate/pageio'
require 'rocuses/graphtemplate/filesystemsize'
require 'rocuses/graphtemplate/filesystemfiles'
require 'rocuses/graphtemplate/diskiocount'
require 'rocuses/graphtemplate/diskiosize'
require 'rocuses/graphtemplate/linuxdiskiowaittime'
require 'rocuses/graphtemplate/linuxdiskioqueuelength'
require 'rocuses/graphtemplate/traffic'
require 'rocuses/graphtemplate/nicerror'
require 'rocuses/graphtemplate/bind'
require 'rocuses/graphtemplate/bindcache'
require 'rocuses/graphtemplate/bindquery'
require 'rocuses/graphtemplate/openldapconnection'
require 'rocuses/graphtemplate/openldapconcurrentconnection'
require 'rocuses/graphtemplate/openldapoperation'
require 'rocuses/graphtemplate/openldapcache'
require 'rocuses/graphtemplate/manager'

